### ISSUE TITLE
关于condition和diffusion模型的性能问题

### ISSUE THREAD

**Issue by nanless** [judiebig/DR-DiffuSE#1]
你好！很感谢作者开源代码！我在使用你的代码复现的时候，发现condition网络本身的性能，PESQ已经在3以上了，好奇是不是diffusion模型在性能这方面相较之下没有什么提升？希望得到回复，谢谢！

**Comment by judiebig** [comment]
是的，如果只是在seen场景下，性能基本没有提升（根据prev文献的描述，普遍认为generative models鲁棒性要强于deterministic NN）；您可以把我们的方法理解成用conditional generative models做数据增强，通过conditional diffusion enhancement model生成的数据来增加deterministic model在unseen场景的鲁棒性（我们重用了condition generation network作为refinement network），您可以把我们的方法和adversarial training建立联系。
