### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by HeChengHui** [judiebig/DR-DiffuSE#2]
@judiebig 
Thank you for your work!

I am interested to test this and i wonder if it is possible for you to release your pretrained models as well.

**Comment by judiebig** [comment]
Apologies for the delayed response... I'm currently fully engaged in other papers/projects (deadlines are approaching), so there might be a delay before I can update this repository. I will make every effort to upload the pre-trained model before November 1st...

You can also train the model using the instructions provided in the readme file (if urgently needed). Feel free to contact me if you have any further questions!
