### ISSUE TITLE
How can i get an wav file during inference?

### ISSUE THREAD

**Issue by KappyDays** [judiebig/DR-DiffuSE#3]
Thank you for the good project.

I want to know how to generate the wav file during the execution of the test_ddpm.py(inference).

**Comment by judiebig** [comment]
Thank you for your attention！

You need to write a function by yourself. You can copy the code from the function "compare_complex" (line 399, ddpm_trainer.py), which transforms the spectrogram to waveform and calculates metrics in the time domain.

In detailed, you need to first apply inverse normalization (lines 535-552, metric.py), then use iSTFT to transform the sepctrogram to waveform (lines 557-567,  metric.py).

**Comment by KappyDays** [comment]
Thank you for your quick reply and good response.
